import {
  ZodArray,
  ZodBoolean,
  ZodDefault,
  ZodEnum,
  ZodNullable,
  ZodNumber,
  ZodObject,
  ZodOptional,
  ZodString,
  ZodType,
} from "zod";

/**
 * Generates plausible placeholder data that satisfies an arbitrary Zod
 * schema, so MockAIProvider can support any structured-generation call
 * site (campaigns, SEO, recommendations, ...) without a bespoke mock per
 * schema. Field names are used as light hints to make output read
 * naturally (e.g. a field called "headline" gets headline-shaped text).
 */
export function mockFromZodSchema<T>(schema: ZodType<T>, fieldName = "value", seed = ""): T {
  return generate(schema, fieldName, seed) as T;
}

function generate(schema: ZodType<any>, fieldName: string, seed: string): unknown {
  if (schema instanceof ZodOptional) return generate(schema.unwrap(), fieldName, seed);
  if (schema instanceof ZodNullable) return generate(schema.unwrap(), fieldName, seed);
  if (schema instanceof ZodDefault) return generate(schema.removeDefault(), fieldName, seed);

  if (schema instanceof ZodObject) {
    const shape = schema.shape;
    const result: Record<string, unknown> = {};
    for (const key of Object.keys(shape)) {
      result[key] = generate(shape[key], key, seed);
    }
    return result;
  }

  if (schema instanceof ZodArray) {
    const count = fieldName.toLowerCase().includes("hashtag") ? 5 : 2;
    return Array.from({ length: count }, (_, i) => generate(schema.element, fieldName, `${seed}-${i}`));
  }

  if (schema instanceof ZodEnum) {
    const options = schema.options as string[];
    return options[0];
  }

  if (schema instanceof ZodNumber) {
    return 75;
  }

  if (schema instanceof ZodBoolean) {
    return true;
  }

  if (schema instanceof ZodString) {
    return mockString(fieldName, seed);
  }

  return null;
}

function mockString(fieldName: string, seed: string): string {
  const key = fieldName.toLowerCase();
  const suffix = seed ? ` ${seed.replace(/^-/, "#")}` : "";

  if (key.includes("hashtag")) return `#MockMarketing${suffix.replace(/\s/g, "")}`;
  if (key.includes("headline")) return `[MOCK] Introducing a better way to get things done${suffix}`;
  if (key.includes("hook")) return `[MOCK] Stop scrolling — this changes everything${suffix}`;
  if (key.includes("cta")) return `[MOCK] Shop now`;
  if (key.includes("caption") || key.includes("body") || key.includes("post") || key.includes("copy")) {
    return `[MOCK] This is AI-generated placeholder copy${suffix} highlighting the key benefits for your audience. Generated by MockAIProvider — connect an AI_PROVIDER=openai key for real output.`;
  }
  if (key.includes("title")) return `[MOCK] A Compelling Title${suffix}`;
  if (key.includes("meta") && key.includes("description")) {
    return `[MOCK] A concise, keyword-aware meta description under 160 characters.${suffix}`;
  }
  if (key.includes("keyword")) return `mock keyword${suffix}`;
  if (key.includes("concept") || key.includes("direction") || key.includes("strategy") || key.includes("message")) {
    return `[MOCK] A clear creative concept tailored to the brand and objective${suffix}.`;
  }
  if (key.includes("explanation") || key.includes("reason")) {
    return `[MOCK] This recommendation is based on recent performance patterns${suffix}.`;
  }
  if (key.includes("article") || key.includes("outline")) {
    return `[MOCK] Full-length AI-generated content would appear here${suffix}. Connect a real AI provider to generate production content.`;
  }

  return `[MOCK] Generated placeholder text${suffix}`;
}
